# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponMatchups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_weapon_type', models.CharField(db_index=True, max_length=80)),
                ('db_attack', models.CharField(db_index=True, max_length=80)),
                ('db_difficulty', models.CharField(db_index=True, max_length=80)),
                ('db_hitbox', models.CharField(db_index=True, max_length=80)),
                ('db_blocks_dodges', models.CharField(blank=True, max_length=80, null=True)),
                ('db_blocks_shields', models.CharField(blank=True, max_length=80, null=True)),
                ('db_blocks_katana', models.CharField(blank=True, max_length=80, null=True)),
                ('db_blocks_bo', models.CharField(blank=True, max_length=80, null=True)),
                ('db_blocks_rogatina', models.CharField(blank=True, max_length=80, null=True)),
                ('db_blocks_sai', models.CharField(blank=True, max_length=80, null=True)),
                ('db_blocks_spear', models.CharField(blank=True, max_length=80, null=True)),
                ('db_blocks_axe', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
    ]
